Blank: Blank
Confirm_delete: "This action will remove the current content from the website.\nClick on \"Ok\" to proceed, or \"Cancel\" to abort."
new: New
edit: Edit
search: Search
file_manager: File manager
publish: Publish
unpublish: Unpublish
