sudo: false

language: php

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - composer test
