---
all:
  include: data/config/*.yml
  tecnodesign:
    apps-dir: .
    data-dir: data
    config-dir: data/config
    cache-dir: data/cache
    log-dir: data/log
    templates-dir: [ data/templates, src/Tecnodesign/Resources/templates ]
    document-root: data/web
    lib-dir: [ vendor ]
    controller-options:
      class: Tecnodesign_Studio
      static: true
      additional-params: true
      layout: layout
    default-route: run
    routes:
      config:
        class: Tecnodesign_App_Install
        method: config
        static: true
        additional-params: true
        layout: cli
      #schema:
      #  class: Tecnodesign_Database
      #  method: exportSchema
      #  static: true
      #  additional-params: false
      #  layout: cli
