#!/bin/sh
TAG='studio-server=2.5.0'
PID=`pgrep -f "$TAG"`
[ ! -z "$PID" ] && pkill -f "$TAG"
mkdir -p "${0%/*}/data/log"
php -S 127.0.0.1:9999 "${0%/*}/app.php" -s $TAG >> "${0%/*}/data/log/app.log" 2>&1 &
pgrep -f "$TAG"
