Blank: Em branco
Confirm_delete: "This action will remove the current content from the website.\nClick on \"Ok\" to proceed, or \"Cancel\" to abort."
new: Novo
edit: Editar
search: Procurar
file_manager: Gerenciador de arquivos
publish: Publicar
unpublish: Desativar
