<?php

/**
 * PlugintdzRelationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzRelationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzRelationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzRelations');
    }
}