<?php

/**
 * PlugintdzTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzTags');
    }
}