<?php

/**
 * PlugintdzPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzPermissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzPermissions');
    }
}