<?php

/**
 * PlugintdzPermissions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: PlugintdzPermissions.class.php 558 2011-01-12 11:57:59Z capile $
 */
abstract class PlugintdzPermissions extends BasetdzPermissions
{
  public function setCredentials($s)
  {
    if(is_array($s))
    {
      asort($s);
      $s = implode(',',$s);
    }
    return $this->_set('credentials',$s);
  }
  public function preInsert($event)
  {
    $web=(isset($_SERVER['REQUEST_URI']));
    if($web || !strtotime($this->created))
      $this->created = date('Y-m-d H:i:s', time());
    if($web || !strtotime($this->updated))
      $this->updated = date('Y-m-d H:i:s', time());
  }
  public function preUpdate($event)
  {
    $web=(isset($_SERVER['REQUEST_URI']));
    if($web || !strtotime($this->updated))
      $this->updated = date('Y-m-d H:i:s', time());
  }
}