<?php

/**
 * PlugintdzEntriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzEntriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzEntriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzEntries');
    }
}