<?php

/**
 * PlugintdzContentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzContentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzContentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzContents');
    }
}