<?php

/**
 * PlugintdzAccess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PlugintdzAccess extends BasetdzAccess
{
  private static $conn=null;
  public static function connect()
  {
    if(is_null(self::$conn)) self::$conn = Doctrine_Manager::getInstance()->getConnection(sfConfig::get('app_connect_connection_name'));
    return self::$conn;
  }
  public static function query()
  {
    return new Doctrine_RawSql(self::connect());
  }
  public function preInsert($event)
  {
    $web=(isset($_SERVER['REQUEST_URI']));
    if($web || !strtotime($this->created))
      $this->created = date('Y-m-d H:i:s', time());
    if($web || !strtotime($this->updated))
      $this->updated = date('Y-m-d H:i:s', time());
  }
  public function preUpdate($event)
  {
    $web=(isset($_SERVER['REQUEST_URI']));
    if($web || !strtotime($this->updated))
      $this->updated = date('Y-m-d H:i:s', time());
  }

}