<?php

/**
 * PlugintdzPeopleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzPeopleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzPeopleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzPeople');
    }
}