<?php

/**
 * PlugintdzGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzGroups');
    }
}