<?php

/**
 * PlugintdzAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzAccess');
    }
}