<?php

/**
 * PlugintdzDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintdzDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintdzDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintdzDetails');
    }
}