af: Afeganistão
za: África do Sul
ax: Åland, Ilhas
al: Albânia
de: Alemanha
ad: Andorra
ao: Angola
ai: Anguilla
aq: Antárctida
ag: Antigua e Barbuda
an: Antilhas Holandesas
sa: Arábia Saudita
dz: Argélia
ar: Argentina
am: Arménia
aw: Aruba
au: Austrália
at: Áustria
az: Azerbeijão
bs: Bahamas
bh: Bahrain
bd: Bangladesh
bb: Barbados
be: Bélgica
bz: Belize
bj: Benin
bm: Bermuda
by: Bielo-Rússia
bo: Bolívia
ba: Bósnia-Herzegovina
bw: Botswana
bv: Bouvet, Ilha
br: Brasil
bn: Brunei
bg: Bulgária
bf: Burkina Faso
bi: Burundi
bt: Butão
cv: Cabo Verde
kh: Cambodja
cm: Camarões
ca: Canadá
ky: Cayman, Ilhas
kz: Cazaquistão
cf: Centro-africana, República
td: Chade
cz: Checa, República
cl: Chile
cn: China
cy: Chipre
cx: Christmas, Ilha
cc: Cocos, Ilhas
co: Colômbia
km: Comores
cg: Congo, República do
cd: Congo, República Democrática do (antigo Zaire)
ck: Cook, Ilhas
kr: Coreia do Sul
kp: Coreia, República Democrática da (Coreia do Norte)
ci: Costa do Marfim
cr: Costa Rica
hr: Croácia
cu: Cuba
dk: Dinamarca
dj: Djibouti
dm: Dominica
do: Dominicana, República
eg: Egipto
sv: El Salvador
ae: Emiratos Árabes Unidos
ec: Equador
er: Eritreia
sk: Eslováquia
si: Eslovénia
es: Espanha
us: Estados Unidos da América
ee: Estónia
et: Etiópia
fo: Faroe, Ilhas
fj: Fiji
ph: Filipinas
fi: Finlândia
fr: França
ga: Gabão
gm: Gâmbia
gh: Gana
ge: Geórgia
gs: Geórgia do Sul e Sandwich do Sul, Ilhas
gi: Gibraltar
gr: Grécia
gd: Grenada
gl: Gronelândia
gp: Guadeloupe
gu: Guam
gt: Guatemala
gg: Guernsey
gy: Guiana
gf: Guiana Francesa
gw: Guiné-Bissau
gn: Guiné-Conacri
gq: Guiné Equatorial
ht: Haiti
hm: Heard e Ilhas McDonald, Ilha
hn: Honduras
hk: Hong Kong
hu: Hungria
ye: Iémen
in: Índia
id: Indonésia
iq: Iraque
ir: Irão
ie: Irlanda
is: Islândia
il: Israel
it: Itália
jm: Jamaica
jp: Japão
je: Jersey
jo: Jordânia
ki: Kiribati
kw: Kuwait
la: Laos
ls: Lesoto
lv: Letónia
lb: Líbano
lr: Libéria
ly: Líbia
li: Liechtenstein
lt: Lituânia
lu: Luxemburgo
mo: Macau
mk: Macedónia, República da
mg: Madagáscar
my: Malásia
mw: Malawi
mv: Maldivas
ml: Mali
mt: Malta
fk: Malvinas, Ilhas (Falkland)
im: Man, Ilha de
mp: Marianas Setentrionais
ma: Marrocos
mh: Marshall, Ilhas
mq: Martinica
mu: Maurícia
mr: Mauritânia
yt: Mayotte
um: Menores Distantes dos Estados Unidos, Ilhas
mx: México
mm: Myanmar (antiga Birmânia)
fm: Micronésia, Estados Federados da
mz: Moçambique
md: Moldávia
mc: Mónaco
mn: Mongólia
me: Montenegro
ms: Montserrat
na: Namíbia
nr: Nauru
np: Nepal
ni: Nicarágua
ne: Níger
ng: Nigéria
nu: Niue
nf: Norfolk, Ilha
no: Noruega
nc: Nova Caledónia
nz: Nova Zelândia (Aotearoa)
om: Oman
nl: Países Baixos (Holanda)
pw: Palau
ps: Palestina
pa: Panamá
pg: Papua-Nova Guiné
pk: Paquistão
py: Paraguai
pe: Peru
pn: Pitcairn
pf: Polinésia Francesa
pl: Polónia
pr: Porto Rico
pt: Portugal
qa: Qatar
ke: Quénia
kg: Quirguistão
gb: Reino Unido da Grã-Bretanha e Irlanda do Norte
re: Reunião
ro: Roménia
rw: Ruanda
ru: Rússia
eh: Saara Ocidental
as: Samoa Americana
ws: Samoa (Samoa Ocidental)
pm: Saint Pierre et Miquelon
sb: Salomão, Ilhas
kn: São Cristóvão e Névis (Saint Kitts e Nevis)
sm: San Marino
st: São Tomé e Príncipe
vc: São Vicente e Granadinas
sh: Santa Helena
lc: Santa Lúcia
sn: Senegal
sl: Serra Leoa
rs: Sérvia
sc: Seychelles
sg: Singapura
sy: Síria
so: Somália
lk: Sri Lanka
sz: Suazilândia
sd: Sudão
se: Suécia
ch: Suíça
sr: Suriname
sj: Svalbard e Jan Mayen
th: Tailândia
tw: Taiwan
tj: Tajiquistão
tz: Tanzânia
tf: Terras Austrais e Antárticas Francesas (TAAF)
io: Território Britânico do Oceano Índico
tl: Timor-Leste
tg: Togo
tk: Toquelau
to: Tonga
tt: Trindade e Tobago
tn: Tunísia
tc: Turks e Caicos
tm: Turquemenistão
tr: Turquia
tv: Tuvalu
ua: Ucrânia
ug: Uganda
uy: Uruguai
uz: Usbequistão
vu: Vanuatu
va: Vaticano
ve: Venezuela
vn: Vietname
vi: Virgens Americanas, Ilhas
vg: Virgens Britânicas, Ilhas
wf: Wallis e Futuna
zm: Zâmbia
zw: Zimbabwe
